// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import { Capacitor } from "@capacitor/core";
import type { Database } from "./types";

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    throw new Error(
      "Missing Supabase environment variables. Ensure SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY (or VITE_ prefixed versions) are set in your .env file.",
    );
  }

  const isMobile = typeof window !== "undefined" && Capacitor.isNativePlatform();

  const customStorage = isMobile
    ? {
        getItem: (key: string) =>
          import("@capacitor/preferences").then(({ Preferences }) =>
            Preferences.get({ key }).then(({ value }) => value)
          ),
        setItem: (key: string, value: string) =>
          import("@capacitor/preferences").then(({ Preferences }) =>
            Preferences.set({ key, value }).then(() => {})
          ),
        removeItem: (key: string) =>
          import("@capacitor/preferences").then(({ Preferences }) =>
            Preferences.remove({ key }).then(() => {})
          ),
      }
    : typeof window !== "undefined"
    ? localStorage
    : undefined;

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: customStorage as any,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Lazy load db service to prevent circular dependencies at startup
export const getLocalDbService = async () => {
  const { localDbService } = await import("@/services/localDbService");
  return localDbService;
};

class MobileQueryBuilder {
  private tableName: string;
  private realBuilder: any;
  private filters: Array<{ type: string; args: any[] }> = [];

  constructor(tableName: string, realBuilder: any) {
    this.tableName = tableName;
    this.realBuilder = realBuilder;
  }

  select(columns?: string) {
    this.filters.push({ type: "select", args: [columns] });
    this.realBuilder = this.realBuilder.select(columns);
    return this;
  }

  eq(column: string, value: any) {
    this.filters.push({ type: "eq", args: [column, value] });
    this.realBuilder = this.realBuilder.eq(column, value);
    return this;
  }

  gte(column: string, value: any) {
    this.filters.push({ type: "gte", args: [column, value] });
    this.realBuilder = this.realBuilder.gte(column, value);
    return this;
  }

  lte(column: string, value: any) {
    this.filters.push({ type: "lte", args: [column, value] });
    this.realBuilder = this.realBuilder.lte(column, value);
    return this;
  }

  order(column: string, options?: any) {
    this.filters.push({ type: "order", args: [column, options] });
    this.realBuilder = this.realBuilder.order(column, options);
    return this;
  }

  maybeSingle() {
    this.filters.push({ type: "maybeSingle", args: [] });
    this.realBuilder = this.realBuilder.maybeSingle();
    return this;
  }

  single() {
    this.filters.push({ type: "single", args: [] });
    this.realBuilder = this.realBuilder.single();
    return this;
  }

  // To support Await:
  async then(onfulfilled?: (value: any) => any, onrejected?: (reason: any) => any) {
    try {
      // 1. Try online query
      const res = await this.realBuilder;
      if (!res.error && res.data) {
        const localDb = await getLocalDbService();
        const dataArray = Array.isArray(res.data) ? res.data : [res.data];
        
        if (this.tableName === "glucose_entries") {
          await localDb.cacheGlucose(dataArray);
        } else if (this.tableName === "insulin_entries") {
          await localDb.cacheInsulin(dataArray);
        } else if (this.tableName === "weight_entries") {
          await localDb.cacheWeight(dataArray);
        } else if (this.tableName === "profiles") {
          const { data: { user } } = await _supabase!.auth.getUser();
          if (user) {
            await localDb.cacheProfile(user.id, res.data);
          }
        } else if (this.tableName === "smart_scan_readings") {
          await localDb.cacheScanReadings(dataArray);
        }
      }
      return onfulfilled ? onfulfilled(res) : res;
    } catch (err) {
      console.warn(`[OFFLINE] Query to ${this.tableName} failed, falling back to SQLite cache:`, err);
      const localData = await this.executeLocalQuery();
      const res = { data: localData, error: null };
      return onfulfilled ? onfulfilled(res) : res;
    }
  }

  private async executeLocalQuery() {
    const { data: { user } } = await _supabase!.auth.getUser();
    if (!user) return [];

    const localDb = await getLocalDbService();
    let data: any[] = [];
    
    if (this.tableName === "glucose_entries") {
      data = await localDb.getGlucose(user.id);
    } else if (this.tableName === "insulin_entries") {
      data = await localDb.getInsulin(user.id);
    } else if (this.tableName === "weight_entries") {
      data = await localDb.getWeight(user.id);
    } else if (this.tableName === "profiles") {
      const p = await localDb.getProfile(user.id);
      data = p ? [p] : [];
    } else if (this.tableName === "smart_scan_readings") {
      data = await localDb.getScanReadings(user.id);
    }

    // Apply basic filter matching
    for (const filter of this.filters) {
      if (filter.type === "eq") {
        const [col, val] = filter.args;
        data = data.filter((item) => item[col] === val);
      } else if (filter.type === "gte") {
        const [col, val] = filter.args;
        data = data.filter((item) => item[col] >= val);
      } else if (filter.type === "lte") {
        const [col, val] = filter.args;
        data = data.filter((item) => item[col] <= val);
      } else if (filter.type === "order") {
        const [col, options] = filter.args;
        const ascending = options?.ascending ?? true;
        data = [...data].sort((a, b) => {
          if (a[col] < b[col]) return ascending ? -1 : 1;
          if (a[col] > b[col]) return ascending ? 1 : -1;
          return 0;
        });
      }
    }

    // Handle single/maybeSingle result shapes
    const hasSingle = this.filters.some((f) => f.type === "single" || f.type === "maybeSingle");
    if (hasSingle) {
      return data.length > 0 ? data[0] : null;
    }

    return data;
  }
}

class MobileMutationBuilder {
  private tableName: string;
  private method: "update" | "delete";
  private payload?: any;
  private realBuilder: any;
  private filters: Array<{ column: string; value: any }> = [];

  constructor(tableName: string, method: "update" | "delete", realBuilder: any, payload?: any) {
    this.tableName = tableName;
    this.method = method;
    this.realBuilder = realBuilder;
    this.payload = payload;
  }

  eq(column: string, value: any) {
    this.filters.push({ column, value });
    return this;
  }

  async then(onfulfilled?: (value: any) => any, onrejected?: (reason: any) => any) {
    try {
      const localDb = await getLocalDbService();

      if (this.method === "update") {
        if (this.tableName === "profiles" && this.filters.some(f => f.column === "user_id")) {
          const userIdFilter = this.filters.find(f => f.column === "user_id");
          await localDb.runQuery(
            `UPDATE profiles SET name = ?, phone = ?, sync_status = 'pending_sync' WHERE user_id = ?`,
            [this.payload.name, this.payload.phone, userIdFilter!.value]
          );
        } else {
          const cols = Object.keys(this.payload).map(k => `${k} = ?`).join(", ");
          const vals = Object.values(this.payload);
          const whereClause = this.filters.map(f => `${f.column} = ?`).join(" AND ");
          const filterVals = this.filters.map(f => f.value);
          await localDb.runQuery(
            `UPDATE ${this.tableName} SET ${cols}, sync_status = 'pending_sync' WHERE ${whereClause}`,
            [...vals, ...filterVals]
          );
        }
      } else if (this.method === "delete") {
        const whereClause = this.filters.map(f => `${f.column} = ?`).join(" AND ");
        const filterVals = this.filters.map(f => f.value);
        await localDb.runQuery(
          `DELETE FROM ${this.tableName} WHERE ${whereClause}`,
          filterVals
        );
      }

      // Try online query
      let onlineQuery = this.method === "update"
        ? this.realBuilder.update(this.payload)
        : this.realBuilder.delete();

      for (const filter of this.filters) {
        onlineQuery = onlineQuery.eq(filter.column, filter.value);
      }

      const res = await onlineQuery;
      if (!res.error) {
        if (this.method === "update") {
          if (this.tableName === "profiles" && this.filters.some(f => f.column === "user_id")) {
            const userIdFilter = this.filters.find(f => f.column === "user_id");
            await localDb.runQuery(`UPDATE profiles SET sync_status = 'synced' WHERE user_id = ?`, [userIdFilter!.value]);
          } else {
            const whereClause = this.filters.map(f => `${f.column} = ?`).join(" AND ");
            const filterVals = this.filters.map(f => f.value);
            await localDb.runQuery(`UPDATE ${this.tableName} SET sync_status = 'synced' WHERE ${whereClause}`, filterVals);
          }
        }
      }
      return onfulfilled ? onfulfilled(res) : res;
    } catch (err) {
      console.warn(`[OFFLINE] Mutation (${this.method}) on ${this.tableName} failed:`, err);
      const res = { data: this.method === "update" ? this.payload : null, error: null };
      return onfulfilled ? onfulfilled(res) : res;
    }
  }
}

// Import the supabase client like this:
// import { supabase } from "@/db/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(target, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    
    // Intercept 'from' on mobile platforms to inject offline caching proxy
    if (prop === "from" && typeof window !== "undefined" && Capacitor.isNativePlatform()) {
      return (tableName: any) => {
        const realBuilder = (_supabase! as any).from(tableName);
        if (!["glucose_entries", "insulin_entries", "weight_entries", "profiles", "smart_scan_readings"].includes(tableName)) {
          return realBuilder;
        }

        return {
          select: (columns?: string) => {
            return new MobileQueryBuilder(tableName, realBuilder).select(columns);
          },
          insert: async (payload: any) => {
            const payloadArray = Array.isArray(payload) ? payload : [payload];
            const record = {
              id: payloadArray[0].id || crypto.randomUUID(),
              ...payloadArray[0],
            };

            const localDb = await getLocalDbService();
            // Cache locally first
            if (tableName === "glucose_entries") {
              await localDb.cacheGlucose([{ ...record, sync_status: "pending_sync" }]);
            } else if (tableName === "insulin_entries") {
              await localDb.cacheInsulin([{ ...record, sync_status: "pending_sync" }]);
            } else if (tableName === "weight_entries") {
              await localDb.cacheWeight([{ ...record, sync_status: "pending_sync" }]);
            } else if (tableName === "profiles") {
              await localDb.cacheProfile(record.user_id, { ...record, sync_status: "pending_sync" });
            } else if (tableName === "smart_scan_readings") {
              await localDb.cacheScanReadings([{ ...record, sync_status: "pending_sync" }]);
            }

            try {
              const res = await realBuilder.insert(record);
              if (!res.error) {
                if (tableName === "profiles") {
                  await localDb.runQuery(`UPDATE profiles SET sync_status = 'synced' WHERE user_id = ?`, [record.user_id]);
                } else {
                  await localDb.runQuery(`UPDATE ${tableName} SET sync_status = 'synced' WHERE id = ?`, [record.id]);
                }
              }
              return res;
            } catch (err) {
              console.warn(`[OFFLINE] Insert to ${tableName} failed, cached locally:`, err);
              return { data: record, error: null };
            }
          },
          upsert: async (payload: any, options?: any) => {
            const payloadArray = Array.isArray(payload) ? payload : [payload];
            const localDb = await getLocalDbService();
            let existingId = payloadArray[0].id;

            const conflictCols = options?.onConflict
              ? options.onConflict.split(",").map((c: string) => c.trim())
              : [];

            if (!existingId && conflictCols.length > 0) {
              const whereClause = conflictCols.map((c: string) => `${c} = ?`).join(" AND ");
              const whereVals = conflictCols.map((c: string) => payloadArray[0][c]);
              try {
                const existingRows = await localDb.selectQuery(
                  `SELECT id FROM ${tableName} WHERE ${whereClause}`,
                  whereVals
                );
                if (existingRows && existingRows.length > 0) {
                  existingId = existingRows[0].id;
                }
              } catch (err) {
                console.warn("[OFFLINE] Failed to check for existing record in upsert:", err);
              }
            }

            const record = {
              id: existingId || crypto.randomUUID(),
              ...payloadArray[0],
            };
            if (tableName === "glucose_entries") {
              await localDb.cacheGlucose([{ ...record, sync_status: "pending_sync" }]);
            } else if (tableName === "insulin_entries") {
              await localDb.cacheInsulin([{ ...record, sync_status: "pending_sync" }]);
            } else if (tableName === "weight_entries") {
              await localDb.cacheWeight([{ ...record, sync_status: "pending_sync" }]);
            } else if (tableName === "profiles") {
              await localDb.cacheProfile(record.user_id, { ...record, sync_status: "pending_sync" });
            } else if (tableName === "smart_scan_readings") {
              await localDb.cacheScanReadings([{ ...record, sync_status: "pending_sync" }]);
            }

            try {
              const res = await realBuilder.upsert(record);
              if (!res.error) {
                if (tableName === "profiles") {
                  await localDb.runQuery(`UPDATE profiles SET sync_status = 'synced' WHERE user_id = ?`, [record.user_id]);
                } else {
                  await localDb.runQuery(`UPDATE ${tableName} SET sync_status = 'synced' WHERE id = ?`, [record.id]);
                }
              }
              return res;
            } catch (err) {
              console.warn(`[OFFLINE] Upsert to ${tableName} failed, cached locally:`, err);
              return { data: record, error: null };
            }
          },
          update: (payload: any) => {
            return new MobileMutationBuilder(tableName, "update", realBuilder, payload);
          },
          delete: () => {
            return new MobileMutationBuilder(tableName, "delete", realBuilder);
          }
        };
      };
    }

    const value = Reflect.get(_supabase, prop);
    return typeof value === "function" ? value.bind(_supabase) : value;
  },
});
