/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSendPushRouteImport } from './routes/api/send-push'
import { Route as ApiAnalyzeImageRouteImport } from './routes/api/analyze-image'
import { Route as AuthenticatedTrainingRouteImport } from './routes/_authenticated/training'
import { Route as AuthenticatedScannerRouteImport } from './routes/_authenticated/scanner'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedExportRouteImport } from './routes/_authenticated/export'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiAdminResetPasswordRouteImport } from './routes/api/admin/reset-password'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendPushRoute = ApiSendPushRouteImport.update({
  id: '/api/send-push',
  path: '/api/send-push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyzeImageRoute = ApiAnalyzeImageRouteImport.update({
  id: '/api/analyze-image',
  path: '/api/analyze-image',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrainingRoute = AuthenticatedTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScannerRoute = AuthenticatedScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExportRoute = AuthenticatedExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiAdminResetPasswordRoute = ApiAdminResetPasswordRouteImport.update({
  id: '/api/admin/reset-password',
  path: '/api/admin/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/export': typeof AuthenticatedExportRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/scanner': typeof AuthenticatedScannerRoute
  '/training': typeof AuthenticatedTrainingRoute
  '/api/analyze-image': typeof ApiAnalyzeImageRoute
  '/api/send-push': typeof ApiSendPushRoute
  '/api/admin/reset-password': typeof ApiAdminResetPasswordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/export': typeof AuthenticatedExportRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/scanner': typeof AuthenticatedScannerRoute
  '/training': typeof AuthenticatedTrainingRoute
  '/api/analyze-image': typeof ApiAnalyzeImageRoute
  '/api/send-push': typeof ApiSendPushRoute
  '/api/admin/reset-password': typeof ApiAdminResetPasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/export': typeof AuthenticatedExportRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/scanner': typeof AuthenticatedScannerRoute
  '/_authenticated/training': typeof AuthenticatedTrainingRoute
  '/api/analyze-image': typeof ApiAnalyzeImageRoute
  '/api/send-push': typeof ApiSendPushRoute
  '/api/admin/reset-password': typeof ApiAdminResetPasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/export'
    | '/history'
    | '/reports'
    | '/scanner'
    | '/training'
    | '/api/analyze-image'
    | '/api/send-push'
    | '/api/admin/reset-password'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/export'
    | '/history'
    | '/reports'
    | '/scanner'
    | '/training'
    | '/api/analyze-image'
    | '/api/send-push'
    | '/api/admin/reset-password'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/_authenticated/export'
    | '/_authenticated/history'
    | '/_authenticated/reports'
    | '/_authenticated/scanner'
    | '/_authenticated/training'
    | '/api/analyze-image'
    | '/api/send-push'
    | '/api/admin/reset-password'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ApiAnalyzeImageRoute: typeof ApiAnalyzeImageRoute
  ApiSendPushRoute: typeof ApiSendPushRoute
  ApiAdminResetPasswordRoute: typeof ApiAdminResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-push': {
      id: '/api/send-push'
      path: '/api/send-push'
      fullPath: '/api/send-push'
      preLoaderRoute: typeof ApiSendPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analyze-image': {
      id: '/api/analyze-image'
      path: '/api/analyze-image'
      fullPath: '/api/analyze-image'
      preLoaderRoute: typeof ApiAnalyzeImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/training': {
      id: '/_authenticated/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof AuthenticatedTrainingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scanner': {
      id: '/_authenticated/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof AuthenticatedScannerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/export': {
      id: '/_authenticated/export'
      path: '/export'
      fullPath: '/export'
      preLoaderRoute: typeof AuthenticatedExportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/admin/reset-password': {
      id: '/api/admin/reset-password'
      path: '/api/admin/reset-password'
      fullPath: '/api/admin/reset-password'
      preLoaderRoute: typeof ApiAdminResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExportRoute: typeof AuthenticatedExportRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedScannerRoute: typeof AuthenticatedScannerRoute
  AuthenticatedTrainingRoute: typeof AuthenticatedTrainingRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExportRoute: AuthenticatedExportRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedScannerRoute: AuthenticatedScannerRoute,
  AuthenticatedTrainingRoute: AuthenticatedTrainingRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ApiAnalyzeImageRoute: ApiAnalyzeImageRoute,
  ApiSendPushRoute: ApiSendPushRoute,
  ApiAdminResetPasswordRoute: ApiAdminResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
