-- Ensure RLS is enabled on all tables
ALTER TABLE IF EXISTS public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.glucose_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.insulin_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.weight_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.push_tokens ENABLE ROW LEVEL SECURITY;
